name: Push Docker Image to ghcr.io

# Run when release is published
on:
  push:
  workflow_dispatch: # Allow for manual run

jobs:
  build:
    runs-on: ubuntu-latest

    # Minimum required permissions
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to ghcr (automatically uses workflow actor and secret)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up lowercase repository name
        run: |
          echo "REPO_LOWERCASE=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWERCASE }}:latest
